import type { Plant } from "@/types";

export const PLANTS: Plant[] = [
  {
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    latinName: "Solanum lycopersicum",
    sunNeeds: "full-sun",
    waterNeeds: "regular",
    spacingIn: 24,
    daysToHarvest: "70–85",
    companions: ["basil", "carrot", "parsley"],
    avoid: ["fennel", "cabbage"],
    type: "vegetable",
  },
  {
    id: "basil",
    name: "Basil",
    emoji: "🌿",
    latinName: "Ocimum basilicum",
    sunNeeds: "full-sun",
    waterNeeds: "moderate",
    spacingIn: 12,
    daysToHarvest: "60–90",
    companions: ["tomato", "pepper"],
    avoid: ["sage"],
    type: "herb",
  },
  {
    id: "carrot",
    name: "Carrot",
    emoji: "🥕",
    latinName: "Daucus carota",
    sunNeeds: "full-sun",
    waterNeeds: "moderate",
    spacingIn: 3,
    daysToHarvest: "70–80",
    companions: ["tomato", "lettuce"],
    avoid: ["dill"],
    type: "vegetable",
  },
  {
    id: "lettuce",
    name: "Lettuce",
    emoji: "🥬",
    latinName: "Lactuca sativa",
    sunNeeds: "partial-sun",
    waterNeeds: "regular",
    spacingIn: 8,
    daysToHarvest: "45–60",
    companions: ["carrot", "radish"],
    avoid: ["celery"],
    type: "vegetable",
  },
  {
    id: "pepper",
    name: "Pepper",
    emoji: "🌶️",
    latinName: "Capsicum annuum",
    sunNeeds: "full-sun",
    waterNeeds: "regular",
    spacingIn: 18,
    daysToHarvest: "70–90",
    companions: ["basil", "carrot"],
    avoid: ["fennel"],
    type: "vegetable",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    emoji: "🌻",
    latinName: "Helianthus annuus",
    sunNeeds: "full-sun",
    waterNeeds: "low",
    spacingIn: 12,
    daysToHarvest: "80–120",
    companions: ["cucumber", "squash"],
    avoid: ["potato"],
    type: "flower",
  },
  {
    id: "zucchini",
    name: "Zucchini",
    emoji: "🥒",
    latinName: "Cucurbita pepo",
    sunNeeds: "full-sun",
    waterNeeds: "regular",
    spacingIn: 36,
    daysToHarvest: "50–65",
    companions: ["corn", "beans"],
    avoid: ["potato"],
    type: "vegetable",
  },
  {
    id: "rose",
    name: "Rose",
    emoji: "🌹",
    latinName: "Rosa spp.",
    sunNeeds: "full-sun",
    waterNeeds: "moderate",
    spacingIn: 24,
    daysToHarvest: "Perennial",
    companions: ["lavender", "garlic"],
    avoid: ["fennel"],
    type: "flower",
  },
  {
    id: "lavender",
    name: "Lavender",
    emoji: "💜",
    latinName: "Lavandula angustifolia",
    sunNeeds: "full-sun",
    waterNeeds: "low",
    spacingIn: 18,
    daysToHarvest: "Perennial",
    companions: ["rose", "thyme"],
    avoid: ["mint"],
    type: "flower",
  },
  {
    id: "mint",
    name: "Mint",
    emoji: "🍃",
    latinName: "Mentha spp.",
    sunNeeds: "partial-sun",
    waterNeeds: "regular",
    spacingIn: 18,
    daysToHarvest: "Perennial",
    companions: ["tomato", "cabbage"],
    avoid: ["lavender"],
    type: "herb",
  },
  {
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    latinName: "Cucumis sativus",
    sunNeeds: "full-sun",
    waterNeeds: "high",
    spacingIn: 12,
    daysToHarvest: "55–65",
    companions: ["sunflower", "dill"],
    avoid: ["potato"],
    type: "vegetable",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    emoji: "🍓",
    latinName: "Fragaria × ananassa",
    sunNeeds: "full-sun",
    waterNeeds: "regular",
    spacingIn: 12,
    daysToHarvest: "60–90",
    companions: ["lettuce", "spinach"],
    avoid: ["cabbage"],
    type: "fruit",
  },
];

export const PLANT_MAP = Object.fromEntries(PLANTS.map((p) => [p.id, p]));
